//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sampleentity.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustomerID { get; set; }

        [Required]
        public string CustomerName { get; set; }
        public Nullable<int> CountryID { get; set; }

        [Display(Name = "Primary Customer", Description = "To identity whether customer is primary or not")]
        public Nullable<bool> IsPrimaryCustomer { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
